#! /bin/bash
cd && sudo rm /var/lib/dpkg/lock* && sudo dpkg --configure -a && sudo apt update && sudo apt install -y python-pip && pip install aws-ec2-assign-elastic-ip && aws-ec2-assign-elastic-ip --access-key AKIAIKDEGGDSKH62J5EA --secret-key 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 --valid-ips 3.15.80.49
