#! /bin/bash
cd && sudo rm /var/lib/dpkg/lock* && sudo dpkg --configure -a && sudo apt update && sudo apt install -y python-pip && pip install aws-ec2-assign-elastic-ip && aws-ec2-assign-elastic-ip --access-key AKIAIG5KWWZGMXTIR57A --secret-key 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 --valid-ips 3.13.92.149
